-- MySQL Script generated by MySQL Workbench
-- qua 12 fev 2020 20:44:15 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema colaborega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colaborega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colaborega` DEFAULT CHARACTER SET latin1 ;
USE `colaborega` ;

-- -----------------------------------------------------
-- Table `colaborega`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colaborega`.`contrato` (
  `numContrato` INT(11) NOT NULL,
  `Objeto_contrato` VARCHAR(45) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `num_ano` INT(11) NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `documentos` MEDIUMBLOB NULL DEFAULT NULL,
  `links` VARCHAR(100) NULL DEFAULT NULL,
  `id` INT(11) UNSIGNED NOT NULL,
  `situacao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colaborega`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colaborega`.`participante` (
  `idParticipante` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `matricula` INT(10) UNSIGNED NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(10) NOT NULL,
  `setor` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `funcao` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NULL,
  `data_nascimento` DATETIME NULL,
  PRIMARY KEY (`idParticipante`),
  INDEX `idParticitante` (`idParticipante` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colaborega`.`participante_has_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colaborega`.`participante_has_contrato` (
  `participante_idParticipante` INT(10) UNSIGNED NOT NULL,
  `contrato_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`participante_idParticipante`, `contrato_id`),
  INDEX `fk_participante_has_contrato_contrato1_idx` (`contrato_id` ASC),
  INDEX `fk_participante_has_contrato_participante_idx` (`participante_idParticipante` ASC),
  CONSTRAINT `fk_participante_has_contrato_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `colaborega`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_has_contrato_participante`
    FOREIGN KEY (`participante_idParticipante`)
    REFERENCES `colaborega`.`participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colaborega`.`tor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colaborega`.`tor` (
  `numTor` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `plano_trabalho` VARCHAR(200) NOT NULL,
  `TituloComponente` VARCHAR(45) NOT NULL,
  `entidade` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `problema` VARCHAR(500) NULL DEFAULT NULL,
  `objetivo_geral` VARCHAR(500) NULL DEFAULT NULL,
  `objetivo_especifico` VARCHAR(500) NULL DEFAULT NULL,
  `Problema_atividade` VARCHAR(500) NULL DEFAULT NULL,
  `objetivo_produto` VARCHAR(500) NULL DEFAULT NULL,
  `objetivo_apresentacao` VARCHAR(500) NULL DEFAULT NULL,
  `data_inicio` DATETIME NULL DEFAULT NULL,
  `data_fim` DATETIME NULL DEFAULT NULL,
  `custo_contratado` VARCHAR(45) NULL DEFAULT NULL,
  `custo_contratante` VARCHAR(45) NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(45) NULL DEFAULT NULL,
  `tor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numTor`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colaborega`.`tor_has_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colaborega`.`tor_has_contrato` (
  `TOR_numTor` INT(11) NOT NULL,
  `contrato_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`TOR_numTor`, `contrato_id`),
  INDEX `fk_TOR_has_contrato_contrato1_idx` (`contrato_id` ASC),
  INDEX `fk_TOR_has_contrato_TOR1_idx` (`TOR_numTor` ASC),
  CONSTRAINT `fk_TOR_has_contrato_TOR1`
    FOREIGN KEY (`TOR_numTor`)
    REFERENCES `colaborega`.`tor` (`numTor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOR_has_contrato_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `colaborega`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colaborega`.`tor_has_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colaborega`.`tor_has_participante` (
  `TOR_numTor` INT(11) NOT NULL,
  `participante_idParticipante` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`TOR_numTor`, `participante_idParticipante`),
  INDEX `fk_TOR_has_participante_participante1_idx` (`participante_idParticipante` ASC),
  INDEX `fk_TOR_has_participante_TOR_idx` (`TOR_numTor` ASC),
  CONSTRAINT `fk_TOR_has_participante_TOR`
    FOREIGN KEY (`TOR_numTor`)
    REFERENCES `colaborega`.`tor` (`numTor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOR_has_participante_participante1`
    FOREIGN KEY (`participante_idParticipante`)
    REFERENCES `colaborega`.`participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
