-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 20:47:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TOR` (
  `numTor` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `plano_trabalho` VARCHAR(200) NOT NULL,
  `TituloComponente` VARCHAR(45) NOT NULL,
  `entidade` VARCHAR(45) NULL,
  `endereco` VARCHAR(200) NULL,
  `nome` VARCHAR(100) NULL,
  `telefone` VARCHAR(15) NULL,
  `problema` VARCHAR(500) NULL,
  `objetivo_geral` VARCHAR(500) NULL,
  `objetivo_especifico` VARCHAR(500) NULL,
  `Problema_atividade` VARCHAR(500) NULL,
  `objetivo_produto` VARCHAR(500) NULL,
  `objetivo_apresentacao` VARCHAR(500) NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  `custo_contratado` VARCHAR(45) NULL,
  `custo_contratante` VARCHAR(45) NULL,
  `forma_pagamento` VARCHAR(45) NULL,
  `tor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numTor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`participante` (
  `idParticipante` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `matricula` INT(10) UNSIGNED NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(10) NOT NULL,
  `setor` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `funcao` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParticipante`),
  INDEX `idParticitante` (`idParticipante` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`TOR_has_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TOR_has_participante` (
  `TOR_numTor` INT NOT NULL,
  `participante_idParticipante` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`TOR_numTor`, `participante_idParticipante`),
  INDEX `fk_TOR_has_participante_participante1_idx` (`participante_idParticipante` ASC) VISIBLE,
  INDEX `fk_TOR_has_participante_TOR_idx` (`TOR_numTor` ASC) VISIBLE,
  CONSTRAINT `fk_TOR_has_participante_TOR`
    FOREIGN KEY (`TOR_numTor`)
    REFERENCES `mydb`.`TOR` (`numTor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOR_has_participante_participante1`
    FOREIGN KEY (`participante_idParticipante`)
    REFERENCES `tcc`.`participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`contrato` (
  `numContrato` INT(11) NOT NULL,
  `Objeto_contrato` VARCHAR(45) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `num_ano` INT(11) NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `documentos` MEDIUMBLOB NULL DEFAULT NULL,
  `links` VARCHAR(100) NULL DEFAULT NULL,
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `situacao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`TOR_has_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TOR_has_contrato` (
  `TOR_numTor` INT NOT NULL,
  `contrato_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`TOR_numTor`, `contrato_id`),
  INDEX `fk_TOR_has_contrato_contrato1_idx` (`contrato_id` ASC) VISIBLE,
  INDEX `fk_TOR_has_contrato_TOR1_idx` (`TOR_numTor` ASC) VISIBLE,
  CONSTRAINT `fk_TOR_has_contrato_TOR1`
    FOREIGN KEY (`TOR_numTor`)
    REFERENCES `mydb`.`TOR` (`numTor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOR_has_contrato_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `tcc`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`participante_has_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`participante_has_contrato` (
  `participante_idParticipante` INT(10) UNSIGNED NOT NULL,
  `contrato_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`participante_idParticipante`, `contrato_id`),
  INDEX `fk_participante_has_contrato_contrato1_idx` (`contrato_id` ASC) VISIBLE,
  INDEX `fk_participante_has_contrato_participante_idx` (`participante_idParticipante` ASC) VISIBLE,
  CONSTRAINT `fk_participante_has_contrato_participante`
    FOREIGN KEY (`participante_idParticipante`)
    REFERENCES `tcc`.`participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_has_contrato_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `tcc`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
